Refine script.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,8 +6,8 @@ on:
       - v1*
 
 jobs:
-  k8s:
-    name: release-k8s
+  deploy:
+    name: release
     runs-on: ubuntu-20.04
 
     steps:
@@ -82,4 +82,10 @@ jobs:
                 registry.cn-hangzhou.aliyuncs.com/ossrs/versions:$SRS_MAJOR
             END
             bash /root/restart_docs-srsversion.sh
+            #
+            # Cleanup old docker images.
+            for image in $(docker images |grep '<none>' |awk '{print $3}'); do
+              docker rmi -f $image
+              echo "Remove image $image, r0=$?"
+            done
 
